server:
  port: 9081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/ly_item?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.leyou.item.entity
